import { EducationType } from "../types/education";

export const education: Array<EducationType> = [
  {
    name: "Software Engineering Student",
    institution: "State University of Novi Pazar, Serbia",
    progression: 33.3,
    type: "University Course",
    teacher: "N/A",
    skills: [
      "Software Engineering",
      "Advanced Algorithms",
      "Competitive Programming",
      "System Design",
      "Data Structures Mastery",
      "Version Control (Git)",
      "Debugging & Troubleshooting",
      "Agile Methodologies",
      "Design Patterns",
      "Software Development Life Cycle",
      "Collaborative Project Management",
    ],
  },
  {
    name: "Social Sciences and Languages track",
    institution: "Gymnasium High School in Novi Pazar, Serbia",
    progression: 100,
    type: "High School Track",
    teacher: "N/A",
    skills: [
      "Communication",
      "Critical Thinking",
      "Cultural Awareness",
      "Multilingualism",
      "Historical Analysis",
      "Research Methods",
      "Ethical Reasoning",
      "Public Speaking",
      "Interpersonal Skills",
      "Creative Writing",
    ],
  },
  {
    name: "Next.js 15 & React - The Complete Guide",
    institution: "Udemy",
    progression: 20,
    type: "Online Course",
    teacher: "Maximilian Schwarzmüller",
    skills: [
      "Next.js",
      "React",
      "JavaScript",
      "Front-End Development",
      "UI/UX Design",
      "Component-based Architecture",
      "Responsive Web Design",
      "State Management",
      "SEO Techniques",
      "Modern Web Optimization",
    ],
  },
  {
    name: "MongoDB - The Complete Developer's Guide 2025",
    institution: "Udemy",
    progression: 61,
    type: "Online Course",
    teacher: "Academind (by Maximilian Schwarzmüller)",
    skills: [
      "MongoDB",
      "NoSQL",
      "Data Modeling",
      "CRUD Operations",
      "Database Performance Optimization",
      "Schema Design",
      "Data Indexing",
      "Aggregation Framework",
      "Scalability Techniques",
      "High Availability Solutions",
    ],
  },
  {
    name: "NodeJS - The Complete Guide (MVC, REST APIs, GraphQL, Deno)",
    institution: "Udemy",
    progression: 100,
    type: "Online Course",
    teacher: "Academind (by Maximilian Schwarzmüller)",
    skills: [
      "Node.js",
      "REST APIs",
      "MVC Architecture",
      "GraphQL",
      "Deno",
      "Backend Development",
      "Server-Side Rendering",
      "Microservices Architecture",
      "Asynchronous Programming",
      "Test-Driven Development",
    ],
  },
  {
    name: "React - The Complete Guide 2025 (Incl. Next.js, Redux)",
    institution: "Udemy",
    progression: 100,
    type: "Online Course",
    teacher: "Academind (by Maximilian Schwarzmüller)",
    skills: [
      "React",
      "Next.js",
      "Redux",
      "Front-End Development",
      "Hooks & Context API",
      "Responsive Web Design",
      "Modern JavaScript",
      "Component Libraries",
      "Progressive Web Apps",
      "Debugging & Optimization",
    ],
  },
  {
    name: "The Complete Javascript Course 2025: From Zero to Expert!",
    institution: "Udemy",
    progression: 100,
    type: "Online Course",
    teacher: "Jonas Schmedtmann",
    skills: [
      "JavaScript",
      "ES6+",
      "Programming Fundamentals",
      "Problem Solving",
      "Functional Programming",
      "Asynchronous Programming",
      "DOM Manipulation",
      "Data Structures in JS",
      "API Integration",
      "Modern Frameworks Overview",
    ],
  },
  {
    name: "100 Days of Code: The Complete Python Pro Bootcamp (29%)",
    institution: "Udemy",
    progression: 29,
    type: "Online Course",
    teacher: "Dr. Angela Yu",
    skills: [
      "Python",
      "Scripting",
      "Automation",
      "Programming Logic",
      "Data Analysis",
      "Web Scraping",
      "Object-Oriented Programming",
      "Debugging Python Code",
      "Popular Python Libraries (Pandas, NumPy)",
      "Algorithmic Thinking",
    ],
  },
  {
    name: "React & TypeScript - The Practical Guide",
    institution: "Udemy",
    progression: 46,
    type: "Online Course",
    teacher: "Academind (by Maximilian Schwarzmüller)",
    skills: [
      "React",
      "Typescript",
      "Programming Logic",
      "Data Visualization",
      "Typescript Best Practices",
      "Clean Code",
    ],
  },
  {
    name: "The Complete React Course",
    institution: "Centar NIT, Serbia",
    progression: 100,
    type: "Live Class",
    teacher: "N/A",
    skills: [
      "React",
      "Web Development",
      "Team Collaboration",
      "Component Architecture",
      "State Management",
      "Lifecycle Methods",
      "Front-End Testing",
      "User Interface Design",
      "Performance Optimization",
      "Agile Project Coordination",
    ],
  },
  {
    name: "The Complete Javascript Course",
    institution: "Centar NIT, Serbia",
    progression: 100,
    type: "Live Class",
    teacher: "N/A",
    skills: [
      "JavaScript",
      "Web Development",
      "Interactive Learning",
      "DOM Manipulation",
      "Event Handling",
      "Asynchronous JS",
      "Functional Programming",
      "Cross-Browser Compatibility",
      "Web APIs Integration",
      "Modern Syntax & Techniques",
    ],
  },
];
