import { TechType } from "../types/tech";
import {
  AISVG,
  AISVG2,
  AlgorithmSVG,
  APISVG,
  BootstrapSVG,
  CloudinarySVG,
  CSSSVG,
  ExpressSVG,
  FireBaseSVG,
  FlaskSVG,
  FramerMotionSVG,
  HTMLSVG,
  JavascriptSVG,
  JWTSVG,
  LocalStorageSVG,
  MaterialUiSVG,
  MongoDBSVG,
  MongooseSVG,
  NextJsSVG,
  NodeJsSVG,
  PythonSVG,
  ReactSVG,
  ReduxSVG,
  RestAPISVG,
  SocketIoSVG,
  SqliteSVG,
  StripeSVG,
  TailwindSVG,
  WebSocketSVG,
} from "./svgs";

export const techSVGS: TechType = {
  "Node.js": NodeJsSVG,
  "Next.js": NextJsSVG,
  Express: ExpressSVG,
  "Material UI": MaterialUiSVG,
  Redux: ReduxSVG,
  React: ReactSVG,
  JavaScript: JavascriptSVG,
  MongoDB: MongoDBSVG,
  "Framer Motion": FramerMotionSVG,
  Firebase: FireBaseSVG,
  API: APISVG,
  "REST API": RestAPISVG,
  JWT: JWTSVG,
  "Socket.IO": SocketIoSVG,
  Cloudinary: CloudinarySVG,
  "Local Storage": LocalStorageSVG,
  "Tailwind CSS": TailwindSVG,
  HTML: HTMLSVG,
  CSS: CSSSVG,
  Stripe: StripeSVG,
  "AI Recommendations": AISVG,
  "AI Integration": AISVG2,
  "Algorithm Visualizer": AlgorithmSVG,
  Mongoose: MongooseSVG,
  WebSockets: WebSocketSVG,
  Flask: FlaskSVG,
  Sqlite: SqliteSVG,
  Python: PythonSVG,
  Bootstrap: BootstrapSVG,
};
