import {
  FramerMotionSVG,
  LocalStorageSVG,
  CloudinarySVG,
  JavascriptSVG,
  MaterialUiSVG,
  PostgresqlSVG,
  AlgorithmSVG,
  BootstrapSVG,
  WebSocketSVG,
  FireBaseSVG,
  MongooseSVG,
  SocketIoSVG,
  TailwindSVG,
  DrizzleSVG,
  ExpressSVG,
  MongoDBSVG,
  RestAPISVG,
  NextJsSVG,
  NodeJsSVG,
  PythonSVG,
  SqliteSVG,
  StripeSVG,
  FlaskSVG,
  ReactSVG,
  ReduxSVG,
  HTMLSVG,
  NeonSVG,
  AISVG2,
  APISVG,
  CSSSVG,
  JWTSVG,
  AISVG,
} from "./svgs";

export const TECH_ICONS: ITech = {
  "Algorithm Visualizer": AlgorithmSVG,
  "Framer Motion": FramerMotionSVG,
  "Local Storage": LocalStorageSVG,
  "Material UI": MaterialUiSVG,
  "Tailwind CSS": TailwindSVG,
  "AI Recommendations": AISVG,
  JavaScript: JavascriptSVG,
  Cloudinary: CloudinarySVG,
  Postgresql: PostgresqlSVG,
  "Socket.IO": SocketIoSVG,
  "AI Integration": AISVG2,
  WebSockets: WebSocketSVG,
  Bootstrap: BootstrapSVG,
  "REST API": RestAPISVG,
  Firebase: FireBaseSVG,
  Mongoose: MongooseSVG,
  "Node.js": NodeJsSVG,
  "Next.js": NextJsSVG,
  Express: ExpressSVG,
  MongoDB: MongoDBSVG,
  Drizzle: DrizzleSVG,
  Stripe: StripeSVG,
  Sqlite: SqliteSVG,
  Python: PythonSVG,
  Redux: ReduxSVG,
  React: ReactSVG,
  Flask: FlaskSVG,
  HTML: HTMLSVG,
  Neon: NeonSVG,
  API: APISVG,
  JWT: JWTSVG,
  CSS: CSSSVG,
};
